export const projects = [
  {
    id: "ai-ux-redesign",
    title: "AI-Powered UX Redesign",
    category: "Artificial Intelligence",
    image: "https://picsum.photos/seed/ai/1920/1080",
    description: "Redesigning the user experience for a complex AI platform.",
    overview: "A comprehensive redesign focusing on making AI insights more accessible to non-technical users.",
    role: "Lead UX Designer",
    timeline: "3 Months",
    tools: ["Figma", "React", "Python"],
    problem: "Users were overwhelmed by the complexity of AI data visualization.",
    solution: "Simplified dashboards with natural language explanations.",
    impact: "40% increase in user engagement.",
  },
  {
    id: "digital-marketing-hub",
    title: "Digital Marketing Hub",
    category: "Digital Marketing",
    image: "https://picsum.photos/seed/marketing/1920/1080",
    description: "A centralized platform for managing multi-channel marketing campaigns.",
    overview: "Streamlining the workflow for marketing teams to launch and track campaigns.",
    role: "Product Designer",
    timeline: "6 Months",
    tools: ["Figma", "Miro", "Jira"],
    problem: "Marketing teams were using fragmented tools, leading to data silos.",
    solution: "A unified hub that integrates all marketing channels.",
    impact: "Saved 15 hours per week for marketing managers.",
  },
  {
    id: "interactive-museum-exp",
    title: "Interactive Museum Experience",
    category: "Interactive Experience",
    image: "https://picsum.photos/seed/museum/1920/1080",
    description: "Creating an immersive digital guide for a modern art museum.",
    overview: "Using AR and interactive kiosks to enhance the museum visitor journey.",
    role: "UX/UI Designer",
    timeline: "4 Months",
    tools: ["Unity", "Figma", "ARKit"],
    problem: "Visitors felt disconnected from the art due to lack of context.",
    solution: "An AR-powered app that provides deep dives into artworks.",
    impact: "95% positive visitor feedback.",
  },
];
